### ISSUE TITLE
discover signature paths

### ISSUE THREAD

**Issue by miyunari** [miyunari/model-validation-controller#23]
Currently the controller expects a specific path to a model and its signature.

e.g.:
```
apiVersion: rhtas.redhat.com/v1alpha1
kind: ModelValidation
metadata:
  name: demo
spec:
  config:
    sigstoreConfig:
      certificateIdentity: "https://github.com/miyunari/model-validation-controller/.github/workflows/sign-model.yaml@refs/tags/v0.0.2"
      certificateOidcIssuer: "https://token.actions.githubusercontent.com"
  model:
    path: /data/tensorflow_saved_model
    signaturePath: /data/tensorflow_saved_model/model.sig 
```
We would like to provide an option to auto discover both.
